module.exports = {
    tiposDeAcidentes: {
        1: 'COLISÃO LATERAL',
        2: 'ATROPELAMENTO DE CICLISTA',
        3: 'QUEDA DE MOTO',
        4: 'COLISÃO TRASEIRA',
        5: 'COLISÃO FRONTAL',
        6: 'ATROPELAMENTO DE PEDESTRE',
        7: 'COL. OBJETO FIXO',
        8: 'QUEDA DE BICICLETA',
        9: 'CAPOTAMENTO',
        10: 'ATROPELAMENTO DE ANIMAL',
        11: 'ENGAVETAMENTO',
        12: 'OUTROS',
    },
    bairros: {
        1: 'LIBERDADE',
        2: 'SAO JOSE',
        3: 'ALTO BRANCO',
        4: 'CENTENARIO',
        5: 'BODOCONGO',
        6: 'DISTRITO DOS MECANICOS',
        7: 'CENTRO',
        8: 'MALVINAS',
        9: 'COMPLEXO ALUIZIO CAMPOS',
        10: 'PRATA',
        11: 'DINAMERICA',
        12: 'CRUZEIRO',
        13: 'SANTA ROSA',
        14: 'SITIO ESTREITO',
        15: 'CATINGUEIRA',
        16: 'LIGEIRO',
        17: 'GALANTE',
        18: 'undefined',
        19: 'ALTO DE CAMPINA',
        20: 'MONTE CASTELO',
        21: 'SANTA TEREZINHA',
        22: 'ESTAÇAO VELHA',
        23: 'TAMBOR',
        24: 'TRES IRMAS',
        25: 'ITARARE',
        26: 'JOSE PINHEIRO',
        27: 'CATOLE',
        28: 'DISTRITO INDUSTRIAL',
        29: 'GLORIA',
        30: 'VELAME',
        31: 'ACACIO FIGUEIREDO',
        32: 'R',
        33: 'CUITES',
        34: 'CONCEIÇAO',
        35: 'BAIRRO DAS CIDADES',
        36: 'MUTIRAO',
        37: 'CAMPINA GRANDE',
        38: 'SAO JOSE DA MATA',
        39: 'MONTE SANTO',
        40: 'PALMEIRA',
        41: 'SANTO ANTONIO',
        42: 'NOVO CRUZEIRO',
        43: 'JARDIM QUARENTA',
        44: 'JARDIM CONTINENTAL',
        45: 'BELA VISTA',
        46: 'CAOLÉ DE BOA VISTA',
        47: 'NOVA BRASILIA',
        48: 'ALÇA SUDOESTE',
        49: 'BAIRRO DAS NAÇÕES',
        50: 'SANTA CRUZ',
        51: 'NOVA HORIZONTE',
        52: 'BAIRRO UNIVERSITÁRIO',
        53: 'PRESIDENTE MEDICI',
        54: 'SERROTAO',
        55: 'QUARENTA',
        56: 'PORTAL SUDOESTE',
        57: 'SITIO LUCAS',
        58: 'MIRANTE',
        59: 'RAMADINHA',
        60: 'JEREMIAS',
        61: 'PEDREGAL',
        62: 'MAJOR VENEZIANO',
        63: 'CIUTES',
        64: 'CONJUNTO RONALDO CUNHA LIMA',
        65: 'CATOLE DE ZE FERREIRA',
        66: 'JARDIM PAULISTANO',
        67: 'LAGOA DE DENTRO',
        68: 'SEVERINO CABRAL',
        69: 'SITIO SAMAMBAIA',
        70: 'ARAXA',
        71: 'SITIO CAJAZEIRAS',
        72: 'POR TRAS DO MAXXI',
        73: 'CASTELO BRANCO',
        74: 'SÃO JANUARIO',
        75: 'CINZA',
        76: 'JARDIM MENEZES',
        77: 'SITIO SALGADINHO',
        78: 'JENIPAPO',
        79: 'CAPIM GRANDE',
        80: 'JARDIM TAVARES',
        81: 'SÃO ',
        82: 'ROCHA CAVALCANTE',
        83: 'SITIO GASPAR',
        84: 'CATOLE DE BOA VISTA',
        85: 'RESSUREIÇÃO',
        86: 'BELO MONTE',
        87: 'SITIO JENIPAPO',
        88: 'VILA CABRAL DE SANTA TEREZINHA',
        89: 'MULTIRAO',
        90: 'ROSA CRUZ',
        91: 'JARDIM AMERICA',
        92: 'SANDRA CAVALCANTE',
        93: 'ENTRADA DE CAMPINA',
        94: 'ZONA RURAL',
        95: 'GLORIA ',
        96: 'SITIO JORGE',
        97: 'VERDEJANTE',
        98: 'PORTAL CAMPINA',
        99: 'ALTO DA SERRA',
        100: 'SITIO CARDOSO',
        101: 'SAO JANUARIO',
        102: 'SITIO CAPIM GRANDE',
        103: 'BAIRRO DAS NAÇOES',
        104: 'MALVINAS ',
        105: 'SITIO SANTANA',
        106: 'PB 138',
        107: 'GALANTE ',
        108: 'RESSUREIÇAO',
        109: 'JARDIM VERDEJANTE',
        110: 'JARDIM BORBOREMA',
        111: 'NOVO HORIZONTE',
        112: 'MASSAPE',
        113: 'SAO JOSE DA MATA ',
        114: 'ESTREITO',
        115: 'ANTES DE GALANTE',
        116: 'Sitio Lucas',
        117: 'Campina Grande',
        118: 'SITIO MARINHO',
        119: 'CONJUNTO ALAMEDA',
        120: 'SALGADINHO',
        121: 'CONJUNTO CIDADE DE DEUS',
        122: 'ROSA MISTICA',
    },
    corredor: {
        1: 'ASSIS CHATEAUBRIAND',
        2: 'ALMEIDA BARRETO',
        3: 'undefined',
        4: 'FLORIANO PEIXOTO',
        5: 'MANOEL TAVARES',
        6: 'GETULIO CAVALCANTE',
        7: 'NILO PEÇANHA',
        8: 'DINAMERICA',
        9: 'ALMIRANTE BARROSO',
        10: 'COSTA E SILVA',
        11: 'SEVERINO CRUZ',
        12: 'BR 104',
        13: 'BR 230',
        14: 'TRES IRMAS',
        15: 'VIGARIO CALIXTO',
        16: 'APRIGIO VELOSO',
        17: 'ELPIDIO DE ALMEIDA',
        18: 'CARDOSO VIEIRA',
        19: 'CAMPOS SALES ',
        20: 'ENGENHEIRO LOURIVAL DE ANDRADE',
        21: 'JERICO',
        22: 'JOANA DARC',
        23: 'JUSCELINO KUBITSCHEK',
        24: 'RONALDO CUNHA LIMA',
        25: 'PARIS',
        26: 'QUEBRA QUILOS',
        27: 'JOAO SUASSUNA',
        28: 'CICERO ALEXANDRINO',
        29: 'ARROJADO LISBOA',
        30: 'ODON BEZERRA',
        31: 'DAMASCO',
        32: 'RAIMUNDO ALVES DA SILVA',
        33: 'VENANCIO NEIVA',
        34: 'JUVENCIO ARRUDA',
        35: 'CHILE',
        36: 'GILO GUEDES',
        37: 'MANOEL MOTA',
        38: 'FRANCISCO LOPES DE ALMEIDA',
        39: 'SANTO ANTONIO',
        40: 'JABUTICABEIRAS',
        41: 'PEDRO I',
        42: 'JANUNCIO FERREIRA',
        43: 'RODRIGUES ALVES',
        44: 'PEDRO DA COSTA AGRA',
        45: 'RAIMUNDO NONATO DE ARAUJO',
        46: 'GETULIO VARGAS',
        47: 'SIQUEIRA CAMPOS',
        48: 'TREZE DE MAIO',
        49: 'CARLOS FRANCISCO MEDEIROS DE ALMEIDA',
        50: 'PLINIO LEMOS',
        51: 'ROSA LOPES DA SILVA',
        52: 'SEBASTIAO DONATO',
        53: 'PEDRO II',
        54: 'RUA DO SOL',
        55: 'APRIGIO NEPOMUCENO',
        56: 'OTACILIO NEPOMUCENO',
        57: 'PB 138',
        58: 'EPITACIO PESSOA',
        59: 'JOAO PESSOA',
        60: 'JOAO MOURA',
        61: 'ANTENOR NAVARRO',
        62: 'FRANCISCO ALVES',
        63: 'ALAGOAS',
        64: 'SEVERINO BEZERRA CABRAL',
        65: 'MANOEL UCHOA',
        66: 'NOUJAIM HABIB',
        67: 'JOAO QUIRINO',
        68: 'TEXEIRA DE FREITAS',
        69: 'FLORIPEDES COUTINHO',
        70: 'INDIOS CARIRIS',
        71: 'ANTONIO PEREIRA FRUTUOSA',
        72: 'INDIOS PIRAGIBE',
        73: 'FERNANDES VIEIRA',
        74: 'JOAO DA MATA',
        75: 'JOAO WALIG',
        76: 'ANTONIO VILARIN',
        77: 'ANA AZEVEDO',
        78: 'AV PARIS',
        79: 'IRINEU JOFFILY',
        80: 'LINO GOMES',
        81: '15 DE NOVEMBRO',
        82: 'PAULO DE FRONTIN',
        83: 'ANIZIO RODRIGUES SOUZA',
        84: 'FRANCISCO ALVES DA SILVA',
        85: 'ABEL COSTA',
        86: 'GASPARINO BARRETO',
        87: 'JOSE ELPIDIO DA COSTA MONTEIRO',
        88: 'MONTEVIDEU',
        89: 'UMBURANAS',
        90: 'SILVA BARBOSA',
        91: 'MARIA DA GUIA MUNIZ ALBUQUERQUE',
        92: 'PORTUGAL',
        93: 'PROBO CAMARA',
        94: 'SALVINO FIGUEIREDO',
        95: 'PEDRO LEAL',
        96: 'APOLONIA AMORIN',
        97: 'VILA NOVA DA RAINHA',
        98: 'OSWALDO CRUZ',
        99: 'PEDRO OTAVIO DE FARIAS LEITE',
        100: 'TAVARES CAVALCANTE',
        101: 'RIO DE JANEIRO',
        102: 'SERGIPE',
        103: 'MIGUEL COUTO',
        104: 'PARANA',
        105: 'VINTE E SETE DE JULHO',
        106: 'CONEGO PEQUENO',
        107: 'DR. VASCONCELOS',
        108: 'MONTEIRO LOBATO',
        109: 'JOAO FLORENTINO DE CARVALHO',
        110: 'FRANCISCO ANTONIO NASCIMENTO',
        111: 'PEDRO LEAL   ',
        112: 'LUIZA BEZERRA MOTA',
        113: 'CORREDOR',
        114: 'VINTE SETE DE JULHO',
        115: 'ANA DE AZEVEDO',
        116: 'VIGOLVINO VANDERLEY',
        117: 'QUINZE DE NOVEMBRO',
        118: 'JAMILA ABRAAO JORGE',
        119: 'MANOEL GONÇALVES GUIMARAES',
        120: 'BR 230 ',
        121: 'JOANA DARC DE ARRUDA',
        122: 'DUQUE DE CAXIAS',
        123: 'JOAO WALLIG',
        124: 'SILVA JARDIM',
        125: 'LINO GOMES DA SILVA',
        126: 'OLEGARIO MACIEL',
        127: 'DO SOL',
        128: 'ESPIRITO SANTO',
        129: 'MACIEL PINHEIRO',
        130: 'CAMPOS SALES',
        131: 'DR VASCONCELOS',
        132: 'ASSEMBLEIA DE DEUS',
        133: 'CAJAZEIRAS',
        134: 'SANTA CLARA',
        135: 'MANOELTAVERES',
        136: 'EDSON SALES',
        137: 'MAMEDE MOISES RAIA',
        138: 'SITIO MASSAPE',
        139: 'MANOEL JOAQUIM RIBEIRO',
        140: 'MARIA DA GUIA MUNIZ DE ALBUQUERQUE',
        141: 'JOAO CAVALCANTE DE ARRUDA',
        142: 'JOAO ALVES DE LIRA',
        143: 'AGAMENON MAGALHAES',
        144: 'RUA DAS UMBURANAS',
        145: 'VIGOLVINO WANDERLEY',
        146: 'PETROPOLES',
        147: 'SITIO LUCAS',
        148: 'OTAVIO BATISTA CABRAL',
        149: 'MATO GROSSO',
        150: 'Siqueira campos',
        151: 'GONÇALVES DIAS',
        152: 'MINISTRO JOSE AMERICO DE ALMEIDA',
        153: 'ALMEIDA BARRETO ',
        154: 'LUIZ MOTA',
        155: 'SILVA BARBOSA ',
        156: 'RODRIGUES ALVES ',
    }

}